// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD98OPb03Uv-uoN1Qjpiv2G6eZIA_Mopq8',
    appId: '1:475602524447:web:a2f50170ffabc74fe4b82a',
    messagingSenderId: '475602524447',
    projectId: 'sfs-clone',
    authDomain: 'sfs-clone.firebaseapp.com',
    storageBucket: 'sfs-clone.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0STA6bjK5Iu8al2jtBrV2l-M_1cW_Uaw',
    appId: '1:475602524447:android:47547e73c3ac0f00e4b82a',
    messagingSenderId: '475602524447',
    projectId: 'sfs-clone',
    storageBucket: 'sfs-clone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiYiOjXVH03xjfZQMp-QcQd0hrTlq5iYM',
    appId: '1:475602524447:ios:08d677a0ad255484e4b82a',
    messagingSenderId: '475602524447',
    projectId: 'sfs-clone',
    storageBucket: 'sfs-clone.firebasestorage.app',
    iosBundleId: 'com.example.sfs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiYiOjXVH03xjfZQMp-QcQd0hrTlq5iYM',
    appId: '1:475602524447:ios:08d677a0ad255484e4b82a',
    messagingSenderId: '475602524447',
    projectId: 'sfs-clone',
    storageBucket: 'sfs-clone.firebasestorage.app',
    iosBundleId: 'com.example.sfs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD98OPb03Uv-uoN1Qjpiv2G6eZIA_Mopq8',
    appId: '1:475602524447:web:152d54a93c4a8606e4b82a',
    messagingSenderId: '475602524447',
    projectId: 'sfs-clone',
    authDomain: 'sfs-clone.firebaseapp.com',
    storageBucket: 'sfs-clone.firebasestorage.app',
  );
}
